export const stressCases = [
  ["reentrancy-vault", `pragma solidity ^0.8.20; contract V { mapping(address=>uint) b; function d() external payable { b[msg.sender]+=msg.value; } function w() external { uint a=b[msg.sender]; (bool ok,)=msg.sender.call{value:a}(""); require(ok); b[msg.sender]=0; } }`],
  ["tx-origin-auth", `pragma solidity ^0.8.20; contract T { address owner; constructor(){owner=msg.sender;} function drain() external { require(tx.origin==owner); payable(msg.sender).transfer(address(this).balance); } }`],
  ["oracle-spot", `pragma solidity ^0.8.20; interface P{function price() external view returns(uint);} contract O{P p; function borrow(uint a) external view returns(uint){return a*1e18/p.price();}}`],
  ["unprotected-init", `pragma solidity ^0.8.20; contract I{address public owner; function initialize(address o) external { owner=o; } function sweep() external { require(msg.sender==owner); }}`],
  ["unsafe-delegatecall", `pragma solidity ^0.8.20; contract D{function exec(address t, bytes calldata d) external { (bool ok,)=t.delegatecall(d); require(ok); }}`],
  ["no-timelock-owner", `pragma solidity ^0.8.20; contract G{address public oracle; address public owner; constructor(){owner=msg.sender;} function setOracle(address o) external {require(msg.sender==owner); oracle=o;}}`],
  ["rounding-leak", `pragma solidity ^0.8.20; contract R{uint public totalAssets=100; uint public totalSupply=3; function redeem(uint shares) external view returns(uint){return shares*totalAssets/totalSupply+1;}}`],
  ["unbounded-loop", `pragma solidity ^0.8.20; contract L{address[] users; function add(address a) external{users.push(a);} function pay() external{for(uint i;i<users.length;i++){payable(users[i]).transfer(1);}}}`],
  ["unchecked-call", `pragma solidity ^0.8.20; contract C{function send(address to) external payable { to.call{value:msg.value}(""); }}`],
  ["signature-replay", `pragma solidity ^0.8.20; contract S{mapping(address=>uint) bal; function claim(bytes32 h,uint a,bytes calldata sig) external { bal[msg.sender]+=a; }}`],
  ["fee-token-accounting", `pragma solidity ^0.8.20; interface E{function transferFrom(address,address,uint) external returns(bool);} contract F{E t; mapping(address=>uint) shares; function dep(uint a) external{t.transferFrom(msg.sender,address(this),a); shares[msg.sender]+=a;}}`],
  ["timestamp-lottery", `pragma solidity ^0.8.20; contract Lot{function win() external view returns(bool){return uint(block.timestamp)%7==0;}}`],
  ["storage-collision", `pragma solidity ^0.8.20; contract P{address impl; address owner; function up(address i) external {impl=i;} fallback() external payable{(bool ok,)=impl.delegatecall(msg.data); require(ok);}}`],
  ["erc777-hook-risk", `pragma solidity ^0.8.20; contract Hook{mapping(address=>uint) b; function tokensReceived(address u,uint a) external{b[u]+=a;} function withdraw() external{uint a=b[msg.sender]; payable(msg.sender).transfer(a); b[msg.sender]=0;}}`],
  ["force-eth-accounting", `pragma solidity ^0.8.20; contract A{uint public accounted; function deposit() external payable{accounted+=msg.value;} function invariant() external view returns(bool){return address(this).balance==accounted;}}`],
  ["permit-no-nonce", `pragma solidity ^0.8.20; contract P{mapping(address=>uint) allowance; function permit(address owner,address spender,uint amount,bytes calldata sig) external{allowance[spender]=amount;}}`],
  ["mev-slippage", `pragma solidity ^0.8.20; contract Swap{function swap(uint amount,uint price) external pure returns(uint){return amount*price/1e18;}}`],
  ["missing-pause-withdraw", `pragma solidity ^0.8.20; contract Pa{bool paused; mapping(address=>uint)b; modifier notP(){require(!paused);_;} function withdraw() external notP{payable(msg.sender).transfer(b[msg.sender]);}}`],
  ["strong-simple", `pragma solidity ^0.8.20; contract Counter{address public immutable owner; uint256 public count; error OnlyOwner(); constructor(){owner=msg.sender;} function inc() external{if(msg.sender!=owner) revert OnlyOwner(); unchecked{count++;}}}`],
  ["access-control-gap", `pragma solidity ^0.8.20; contract Roles{mapping(address=>bool) admin; function grant(address a) external{admin[a]=true;} function burn(address a,uint v) external{require(admin[msg.sender]);}}`],
];
